name: KBase Narrative Method Store tests

on:
  pull_request:
    types:
    - opened
    - reopened
    - synchronize
    - ready_for_review
  push:
    # run workflow when merging to main or develop
    branches:
      - main
      - master
      - develop

jobs:

  nms_tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          # the current production setup
          - java: '8'
            mongo: 'mongodb-linux-x86_64-3.6.13'
          - java: '11'
            mongo: 'mongodb-linux-x86_64-ubuntu2204-7.0.4'
    steps:
      - uses: actions/checkout@v3

      - name: Set up java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: ${{matrix.java}}

      - name: Install dependencies and set up test config
        shell: bash
        run: |
          export HOMEDIR=`pwd`

          # move to parent dir of homedir to install binaries etc
          cd ..

          # set up mongo
          wget -q http://fastdl.mongodb.org/linux/${{matrix.mongo}}.tgz
          tar xfz ${{matrix.mongo}}.tgz
          export MONGOD=`pwd`/${{matrix.mongo}}/bin/mongod

          # set up test config
          cd $HOMEDIR
          cp -n test.cfg.example test.cfg
          echo "\ntest.mongo-exe-path=$MONGOD\n" >> test.cfg
          cat test.cfg

      - name: Run tests
        shell: bash
        run: ./gradlew test

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true
